import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import{n as t,t as n}from"./assets/vendor-Cx6EavNb.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var r=`55201834-b2019b61559684ce41de74b7e`,i=`https://pixabay.com/api/`;async function a(e,n){let a={key:r,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0,page:n,per_page:15};return(await t.get(i,{params:a})).data}var o=e(n(),1),s=document.querySelector(`.gallery`),c;function l(e){if(e.length===0){u(`Sorry, there are no images matching your search query. Please try again!`);return}let t=e.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
        </a>
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </li>
    `).join(``);s.insertAdjacentHTML(`beforeend`,t),c?c.refresh():c=new window.SimpleLightbox(`.gallery a`,{captionsData:`alt`,captionDelay:250})}function u(e){o.default.info({title:`Info`,message:e,position:`topRight`})}function d(){s.innerHTML=``}function f(){let e=document.querySelector(`.loader`);e.style.display=`block`}function p(){let e=document.querySelector(`.loader`);e.style.display=`none`}function m(){let e=document.querySelector(`.loadmore`);e.style.display=`block`}function h(){let e=document.querySelector(`.loadmore`);e.style.display=`none`}var g=document.querySelector(`.form`),_=document.querySelector(`.loadmore`),v=``,y=1,b=0,x=15;g.addEventListener(`submit`,async e=>{if(e.preventDefault(),v=g.elements[`search-text`].value.trim(),!v){u(`Please enter a search query.`);return}y=1,d(),p(),h(),f();try{let e=await a(v,y);if(b=e.totalHits,b===0){u(`Sorry, there are no images matching your search query. Please try again!`);return}l(e.hits),S()}catch(e){u(`An error occurred while fetching images.`),console.error(e)}finally{p(),g.reset()}}),_.addEventListener(`click`,async()=>{y+=1,f(),h();try{l((await a(v,y)).hits),C(),S()}catch(e){u(`An error occurred while loading more images.`),console.error(e)}finally{p()}});function S(){let e=Math.ceil(b/x);y>=e?(h(),b>0&&u(`We're sorry, but you've reached the end of search results.`)):m()}function C(){let e=document.querySelector(`.gallery-item`);if(e){let{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:`smooth`})}}
//# sourceMappingURL=index.js.map