import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import{n as t,r as n,t as r}from"./assets/vendor-CPGPy-p3.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=`55201834-b2019b61559684ce41de74b7e`,a=`https://pixabay.com/api/`;async function o(e,t=1){let r={key:i,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0,per_page:15,page:t};return(await n.get(a,{params:r})).data}var s=e(t(),1),c=e(r(),1),l=document.querySelector(`.gallery`),u=document.querySelector(`.loader`),d=document.querySelector(`#loadmore-button`),f=new c.default(`.gallery a`,{captionsData:`alt`,captionDelay:250});function p(e){let t=e.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
        </a>
        <div class="image-info">
          <p><span>Likes</span>${e.likes}</p>
          <p><span>Views</span>${e.views}</p>
          <p><span>Comments</span>${e.comments}</p>
          <p><span>Downloads</span>${e.downloads}</p>
        </div>
      </li>
    `).join(``);l.insertAdjacentHTML(`beforeend`,t),f.refresh()}function m(e){s.default.info({message:e,position:`topRight`})}function h(){l.innerHTML=``}function g(){u.style.display=`block`}function _(){u.style.display=`none`}function v(){d.style.display=`block`}function y(){d.style.display=`none`}var b=document.querySelector(`.form`),x=document.querySelector(`#loadmore-button`),S=``,C=1,w=0;y(),b.addEventListener(`submit`,async e=>{if(e.preventDefault(),S=b.elements[`search-text`].value.trim(),!S){m(`Please enter a search query.`);return}C=1,h(),y(),g();try{let e=await o(S,C);w=e.totalHits,e.hits.length===0?m(`Sorry, there are no images matching your search query.`):(p(e.hits),T())}catch{m(`Something went wrong. Please try again later.`)}finally{_(),b.reset()}}),x.addEventListener(`click`,async()=>{C+=1,g(),y();try{p((await o(S,C)).hits),E(),T()}catch{m(`Error loading more images.`)}finally{_()}});function T(){let e=Math.ceil(w/15);C>=e?(y(),w>0&&m(`We're sorry, but you've reached the end of search results.`)):v()}function E(){let e=document.querySelector(`.gallery-item`);if(e){let{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:`smooth`})}}
//# sourceMappingURL=index.js.map